version: "3.8"

services:
  jenkins:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount the Docker socket to allow Jenkins to access Docker
      - jenkins_home:/var/jenkins_home # Mount a persistent volume for Jenkins data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jenkins
    networks:
      - app-network

  node-app:
    image: node:14 # You can use a specific node version here
    container_name: node-app
    working_dir: /app # Set the working directory inside the container
    volumes:
      - ../q4-app:/app # Mount the q4-app directory to /app in the container
    command: |
      bash -c "
        # Start app.js in the background
        node app.js & 
        # Wait for the app to start (adjust the sleep time if needed)
        sleep 10 && 
        # Run ui-test.js after the app is up
        node ui-test.js
      "
    networks:
      - app-network
    depends_on:
      - jenkins # Wait for Jenkins to be ready, if necessary

volumes:
  jenkins_home: # Define a persistent volume for Jenkins data

networks:
  app-network: # Define a custom network for the services to communicate
